/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bma_lua_javalib_LuaState */

#ifndef _Included_bma_lua_javalib_LuaState
#define _Included_bma_lua_javalib_LuaState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bma_lua_javalib_LuaState
 * Method:    _open
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_bma_lua_javalib_LuaState__1open
  (JNIEnv *, jobject, jint);

/*
 * Class:     bma_lua_javalib_LuaState
 * Method:    _destroy
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_bma_lua_javalib_LuaState__1destroy
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     bma_lua_javalib_LuaState
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bma_lua_javalib_LuaState__1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bma_lua_javalib_LuaState
 * Method:    _apiX
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_bma_lua_javalib_LuaState__1apiX
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     bma_lua_javalib_LuaState
 * Method:    _xapi
 * Signature: (JILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_bma_lua_javalib_LuaState__1xapi
  (JNIEnv *, jobject, jlong, jint, jobject, jobject, jobject);

/*
 * Class:     bma_lua_javalib_LuaState
 * Method:    _getDebug
 * Signature: (JLjava/lang/String;I)Lbma/lua/javalib/LuaDebug;
 */
JNIEXPORT jobject JNICALL Java_bma_lua_javalib_LuaState__1getDebug
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     bma_lua_javalib_LuaState
 * Method:    _timeout
 * Signature: (JZI)V
 */
JNIEXPORT void JNICALL Java_bma_lua_javalib_LuaState__1timeout
  (JNIEnv *, jobject, jlong, jboolean, jint);

/*
 * Class:     bma_lua_javalib_LuaState
 * Method:    _writeData
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_bma_lua_javalib_LuaState__1writeData
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     bma_lua_javalib_LuaState
 * Method:    _readData
 * Signature: (JII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_bma_lua_javalib_LuaState__1readData
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
