/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ge_lua_LuaState */

#ifndef _Included_ge_lua_LuaState
#define _Included_ge_lua_LuaState
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_ge_lua_LuaState__1open
  (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_ge_lua_LuaState__1threadInit
  (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_ge_lua_LuaState__1close
  (JNIEnv *, jobject, jlong);

JNIEXPORT jboolean JNICALL Java_ge_lua_LuaState__1addpath
  (JNIEnv *, jobject, jlong, jstring);


JNIEXPORT jboolean JNICALL Java_ge_lua_LuaState__1setvar
  (JNIEnv *, jobject, jlong, jstring, jstring);

JNIEXPORT jboolean JNICALL Java_ge_lua_LuaState__1pcall
  (JNIEnv *, jobject, jlong, jstring, jobject);

JNIEXPORT jstring JNICALL Java_ge_lua_LuaState__1eval
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
